### ISSUE TITLE
login, logout, isAuthenticated functions now added by authenticate(), not initialize()

### ISSUE THREAD

**Issue by hy2850** [jwalton/passport-api-docs#8]
## Problem
Starting from Passport v0.5.1 (2021-12-15),  `login()`, `logIn()`, `logout()`, `logOut()`, `isAuthenticated()`, and `isUnauthenticated()` functions are added to request object by `authenticate()`, not `initialize()`

Passport Changelog:   https://github.com/jaredhanson/passport/blob/master/CHANGELOG.md#051---2021-12-15

Passport commits related to this changelog
https://github.com/jaredhanson/passport/commit/77ee3a6df512452f04d84478aac9c477233d1807

<br>

## What to do
Parts of the manual (below) need to be updated to reflect these changes.  

1. passport.initialize → remove below description
> This will also set up req.login() and req.logout().

https://github.com/jwalton/passport-api-docs/commit/cc0a3e0cba96f4effa1629f7ea93d27848d27736#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R19

2. passport.authenticate →  
Add that 'helper functions' (login, logout, isAuthenticated, isUnauthenticated) are attached to `req` object by `passport.authenticate`

**Comment by jwalton** [comment]
Thanks for pointing this out!  I've switched to a new employer where we use Auth0 instead of Passport, so I haven't been following it as closely.

**Comment by jwalton** [comment]
Hopefully I didn't butcher the Russian version too much.  :P
